### ISSUE TITLE
Aerial Display optimization

### ISSUE THREAD

**Issue by srlenard** [NYCPlanning/labs-citymap#178] opened 2018-05-21 20:17 UTC
Two things to make the aerials display better. 
 We need to turn off the alteration map layer when someone turns on the aerial layer.  We can allow them to turn it back on, but it overlays a transparency on the aerial that makes it hard to read the aerial.  

Next, we need to make the basemap lines yellow to show up against the aerial.

**Comment by RonthePlanner** [comment] 2018-07-24 19:04
I inquired about this as well via e-mail.  "For these eyes - the tax lines are too light.   Street lines should be visible at all times - the need to hover over street lines in aerial view is very limiting.  

Overall, these two items makes this much less useful than the Zoning Application for me"

**Comment by trbmcginnis** [comment] 2018-09-13 18:35
Duplicate of #226

**Closed by trbmcginnis** 2018-09-13 18:35 UTC
Labels: enhancement, feedback
