### ISSUE TITLE
Highlight pdf’s respective geometry on hover

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-citymap#73] opened 2018-04-13 19:18 UTC
#### User Story
As a {type of user}, I want {some goal} so that {some reason}

#### Description
What's it all about?

#### How to reproduce this bug:

1. Step one
2. ???
3. Error

**Comment by andycochran** [comment] 2018-04-16 17:10
Duplicate of #52

**Closed by andycochran** 2018-04-16 17:10 UTC
