### ISSUE TITLE
Change linetypes dynamically to optimize visibility over aerials

### ISSUE THREAD

**Issue by srlenard** [NYCPlanning/labs-citymap#203] opened 2018-06-06 19:35 UTC
Change mapped streets, unmapped streets, and street treatment lines to show yellow when arials are turned on.  Yellow shows well against both light and dark portions of photos.

**Comment by trbmcginnis** [comment] 2018-09-13 19:10
duplicate of #226

**Closed by trbmcginnis** 2018-09-13 19:10 UTC
Labels: design, feedback
