### ISSUE TITLE
prompt user to whitelist

### ISSUE THREAD

**Issue by aenglis** [NYCPlanning/labs-citymap#188] opened 2018-05-29 18:02 UTC
Popup blockers are prevalent. We need to have something to alert new users to whitelist the site in order for things to work correctly.

**Comment by andycochran** [comment] 2018-05-31 19:58
Duplicate of https://github.com/NYCPlanning/labs-mapboxgl-print-service/issues/9

**Closed by andycochran** 2018-05-31 19:58 UTC
